version: "3"

volumes:
  db-data:

services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/lotos-checker'
    environment:
      DATABASE_PASSWORD: $DATABASE_PASSWORD
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - 'db-data:/var/lib/postgresql/data'